
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param amount
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "ConversionEuroToMGA")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToMGA", targetNamespace = "http://ws/", className = "ws.ConversionEuroToMGA")
    @ResponseWrapper(localName = "ConversionEuroToMGAResponse", targetNamespace = "http://ws/", className = "ws.ConversionEuroToMGAResponse")
    @Action(input = "http://ws/BankService/ConversionEuroToMGARequest", output = "http://ws/BankService/ConversionEuroToMGAResponse")
    public Double conversionEuroToMGA(
        @WebParam(name = "amount", targetNamespace = "")
        Double amount);

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws/", className = "ws.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws/", className = "ws.GetAccountResponse")
    @Action(input = "http://ws/BankService/getAccountRequest", output = "http://ws/BankService/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ws.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAccounts", targetNamespace = "http://ws/", className = "ws.ListAccounts")
    @ResponseWrapper(localName = "listAccountsResponse", targetNamespace = "http://ws/", className = "ws.ListAccountsResponse")
    @Action(input = "http://ws/BankService/listAccountsRequest", output = "http://ws/BankService/listAccountsResponse")
    public List<Account> listAccounts();

}
